name: Pruebas Cypress
on:  [push] 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npm run run-all 
