name: Pruebas Cypress
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npx cypress run --record --key 4a40f361-97d1-47e5-b817-218009e87d1f   
