name: Pruebas Cypress

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npm run run-all --headless --timeout 60000

  notify-slack:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Enviar resultado a Slack
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Automation Test Results:\n\nWorkflow ${{ github.workflow }} completed with status: ${{ job.status }}",
            "channel": "@GustavoDurand"
          }' $SLACK_WEBHOOK_URL
