Copy code
name: Pruebas Cypress
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npm run run-all --headless --timeout 10000
      - name: Enviar resultado a Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Automation Test Results:\n\n'"${{ job.status }}"'",
            "channel": "#nombre-del-canal"  // Reemplaza con el nombre de tu canal en Slack
          }' $SLACK_WEBHOOK_URL
